description: ARM Cortex-M
badge_token: QsFQ9CsYegvj7x78qiit

language: objective-c
before_install:
  - brew update
  - brew tap tcr/tcr
  - brew install python gyp ninja gcc-arm node
  - git config credential.helper store
  - git clone https://tmTestUser:tmTestUser1@github.com/tessel/runtime.git deps/runtime
  - git clone https://tmTestUser:tmTestUser1@github.com/tessel/colony-lua.git deps/runtime/deps/colony-lua
install:
  - git submodule update --init
  - npm install
script:
  - make arm

git:
  submodules: false
